name:                chess-tui
version:             0.1.0.0
github:              "Mains03/chess-tui"
license:             BSD3
author:              "Samson Main"
maintainer:          "samsonsmain@gmail.com"
copyright:           "2022 Samson Main"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Mains03/chess-tui#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty

library:
  source-dirs: src

executables:
  chess-tui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-tui

tests:
  chess-tui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-tui
